data_dir: /home/dimuthu1/scratch/PPMI_project2/derivatives/analysis/structural/
analysis_dir: /home/dimuthu1/scratch/PPMI_project2/derivatives/analysis/structural/

participants_tsv: ./cfg/participants_test.tsv

#HCP segmentations in subject native space:
template: ./cfg/MNI_striatum_2mm.nii.gz
dti_img: /home/dimuthu1/scratch/PPMI_project2/derivatives/diffparc_dev/work/{subject}/bedpost.CIT168_striatum_cortical/connMap.4d.nii.gz
seed_img: /home/dimuthu1/scratch/PPMI_project2/derivatives/diffparc_dev/work/{subject}/bedpost.CIT168_striatum_cortical/seed_dtires.nii.gz

Right_mat: connMaps/RH/sub-{subject}-connMap_rh.mat
Left_mat: connMaps/LH/sub-{subject}-connMap_lh.mat


stat_path_lh: /home/dimuthu1/scratch/project2/derivatives/hcp_360/work/MyWorkflow/_sub_id_{subject}/parce/out_put/{subject}/tables/table_lh.txt

stat_path_rh: /home/dimuthu1/scratch/project2/derivatives/hcp_360/work/MyWorkflow/_sub_id_{subject}/parce/out_put/{subject}/tables/table_rh.txt


surf_label_lh: /home/dimuthu1/scratch/project2/Project_2/cfg/surface_labels/mmpL.func.gii
surf_label_rh: /home/dimuthu1/scratch/project2/Project_2/cfg/surface_labels/mmpR.func.gii

HCP_360_labels: /home/dimuthu1/scratch/project2/Project_2/cfg/LUT_HCP-MMP1.txt

#HCP_seg_nii: sub-{subject}/binary/sub-{subject}_exprater_{seed}_{hemi}_bin.nii.gz

#ants transforms from template building - affine and warp are globbed
ants_template_dir: /project/6007967/jclau/snsx32/templates/snsx32_v0.2/snsx32_v0.2_i09
ants_affine_mat: snsx32_v0.2_i09sub-{subject}_acq-MP2RAGE_run-01_T1w*GenericAffine.mat
ants_warp_nii: snsx32_v0.2_i09sub-{subject}_acq-MP2RAGE_run-01_T1w*[0-9]Warp.nii.gz
ants_invwarp_nii: snsx32_v0.2_i09sub-{subject}_acq-MP2RAGE_run-01_T1w*[0-9]InverseWarp.nii.gz
ants_ref_nii: snsx32_v0.2_i09template0.nii.gz


seeds:
 - ZI
 - ZIR
hemis:
 - L
 - R


#targets in subject native space
targets_txt: cfg/hcp_mmp_sym_180.txt
targets_seg_dir: /project/6007967/akhanf/cfmm-bids/data/Khan/SNSX_7T/deriv/freesurfer



#fsl 6.0.1, ants; also:  mri_convert (from freesurfer) reg_resample (niftyreg) 
singularity_neuroglia: /project/6007967/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif 
#singularity_neuroglia: docker://khanlab/neuroglia-core:latest  

max_k: 12

#tractography parameters
probtrack:
    seed_resolution: 0.7
    nsamples: 10000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t --randfib=2' 


enable_dropbox: False
dropbox_token: insert_OAuth2_token_here

